[window]
opacity = 1

padding.x = 12
padding.y = 12

[font]
normal.family = "SF Mono Powerline"
normal.style = "SemiBold"
bold.family = "SF Mono Powerline"
bold.style = "Bold"
size = 11

[cursor]
style.shape = "Block"
style.blinking = "Never"
vi_mode_style.shape = "Block"

[mouse]
hide_when_typing = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#080808"
blue = "#ffb7c5"
cyan = "#ffb7c5"
green = "#8cc85f"
magenta = "#cf87e8"
red = "#ff5454"
white = "#c6c6c6"
yellow = "#e3c78a"

[colors.cursor]
cursor = "#8e8e8e"
text = "#080808"

[colors.normal]
black = "#080808"
blue = "#ffb7c5"
cyan = "#ffb7c5"
green = "#8cc85f"
magenta = "#cf87e8"
red = "#ff5454"
white = "#c6c6c6"
yellow = "#e3c78a"

[colors.primary]
background = "#171717"
bright_foreground = "#eeeeee"
foreground = "#bdbdbd"

[colors.selection]
background = "#b2ceee"
text = "#080808"
